name: trade_tracker
description: A Flutter project for tracking SEC Form 4 filings.
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^0.13.6
  path_provider: ^2.0.11
  xml: ^6.5.0 
  url_launcher: ^6.3.0
  share_plus: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  hive_test: ^1.0.1
  build_runner: ^2.4.11
  hive_generator: ^2.0.0
  flutter_lints: ^3.0.0
  

